# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

#pdf_passage
pdf_passage:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: ../../../pdf_passage.csv

#전체_passage
concat_passage:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: ../../../concat_passage.csv
  
#pdf_passage subtitles
pdf_wt_passage:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: ../../../pdf_wt_passage.csv

#pdf_passage and notice passage
pdf_notice_wt_passage:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: ../../../pdf_notice_wt_passage.csv

#pdf_passage and notice passage subtitles
pdf_notice_subtitle_passage:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: ../../../pdf_notice_subtitle_passage.csv
  